### ISSUE TITLE
benchmarks: msort killed

### ISSUE THREAD

**Issue by umutacar** [MPLLang/mpl-tutorial#1]
this is running on my mac 
within the docker container provided

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/6068765/164231045-97089b51-401a-4b7a-b801-764de8b827c6.png">

**Comment by shwestrick** [comment]
It's probably a memory limit. Docker containers on Mac are more restrictive than on Linux, and are initialized with a pretty small limit (something like just 1 or 2 GB).

As far as I know, you have to use the GUI to increase the memory limit for the container.
